### PR TITLE
Update with google/transit

### PR DESCRIPTION
**Pull request by isabelle-dr**
Update MobilityData's branch with google/transit

### CODE REVIEW

**Comment by isabelle-dr** [comment]
@fredericsimard, is this the proper way to get this fork up-to-date with google/transit master?

It seems weird that we need folks who contributed on google/transit to sign CLAs here.

**Comment by fredericsimard** [comment]
That dates back a while, I see that Sean Barbeau installed this, although I don't know when.

Should I revoke access to it?

CLA

**Comment by fredericsimard** [comment]
And I don't see this repo on the list of CLA setups on the https://cla-assistant.io/ website. Odd...

agreements

**Comment by fredericsimard** [comment]
Ok, so it's safe to remove it. I'll look into how to do this properly.

**Comment by fredericsimard** [comment]
@isabelle-dr I can't remove the CLA assistant because it's not installed/connected to this repo. Perhaps it's a comment that was dragged from somewhere else. I deleted the comment, let's see if it shows up again.

**Comment by isabelle-dr** [comment]
> I deleted the comment

I would have never thought of doing this, elegant solution. Can you approve the PR Fred?

**Review by fredericsimard — APPROVED** [review]
LGTM!

**Pull request merged**
