### PR TITLE
Updating fork with latest upstream content (master branches)

### PR DESCRIPTION
**Pull request by fabrice-v**
Requested by @timMillet 
Instructions followed from here with starting page https://github.com/mobilitydata/transit/compare (no need to follow step 1 `click on compare button`)

https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

### CODE REVIEW

**Comment by barbeau** [comment]
@fabrice-v @timMillet Quick note - you can't use pull requests to update the master branch to match upstream. The reason is that when you merge the PR, it creates a merge commit that then causes this repo's history to diverge again from upstream:

image

And, you can't open a clean PR against the upstream repo or push more changes to the master here after the Git history has diverged.

Easiest way to update master to match upstream is just to use the Git command line and push the upstream branch (or force-push, if you've diverged in this case) to this repo (normally your origin). Typically this would be:
* `git checkout master`
* `git pull upstream master`
* `git push origin master` (you can include ` -f` if needed to force push)

I just did this for the master branch here so this repo history now matches upstream again:

image

**Comment by fabrice-v** [comment]
Oh, thks a lot for that! It is completely my bad as it was a (proven disastrous) first for me. Also thks for fixing it this time and I'll do it through git for future needs.

**Comment by fabrice-v** [comment]
Quick question @barbeau , would have it been correct to use the `squash and merge` Github button to add the PR to the fork so that history wouldn't diverge? Will use the git commands but was curious if there is any way that is more user friendly let say.

**Comment by barbeau** [comment]
@fabrice-v Good question, but no - squash and merge would turn all of the new commits from upstream into a single commit in our fork here, so again the Git histories wouldn't match.

**Comment by fabrice-v** [comment]
Oh alright, got it. Thks!

**Pull request merged**
