### PR TITLE
Add StationUpdate for realtime data for GTFS-Pathways

### PR DESCRIPTION
**Pull request by barbeau**
This PR was created following this [Google Groups discussion](https://groups.google.com/forum/#!topic/gtfs-realtime/icSuTjAYsh8). See the [GTFS-Pathways StationUpdate documentation](https://docs.google.com/document/d/1qJOTe4m_a4dcJnvXYt4smYj4QQ1ejZ8CvLBYzDM5IyM/edit#heading=h.ikb23zeppj2n) for draft proposal with field descriptions.

### CODE REVIEW

**Comment by e-lo** [comment]
What is the status of StationUpdate and what is required to move it forward? Do we just need a producer or a consumer as well?

**Comment by barbeau** [comment]
@e-lo I created this PR as a draft implementation for several folks that had expressed interest in implementing StationUpdates following [this GitHub discussion](https://groups.google.com/forum/#!topic/gtfs-realtime/icSuTjAYsh8). I've posted again to the same thread asking if anyone has made progress towards implementation (I don't know of anyone producing or consuming right now).

We could open this now as an official proposal on the google/transit repo, and we would need at least 3 "yes" votes (with at least 80% yes votes total) to adopt it as [an experimental field](https://github.com/google/transit/blob/master/gtfs-realtime/CHANGES.md#experimental-fields) in GTFS-realtime. To permanently adopt the field in the future, we'd need at least one producer and one consumer and 3 "yes" votes (and 0 "no" votes).

Is StationUpdates something you'd like to see officially adopted as an experimental field? If so we could work on opening the official proposal.

**Comment by opyh** [comment]
This would be good to have for elevator/escalator statuses. We have such data and I'd like to move this forward by trying to produce this data for the VBB (beta) pathways.txt.

**Comment by barbeau** [comment]
Reopening, as it seems this is still relevant along with https://github.com/google/transit/issues/268

**Comment by derhuerst** [comment]
Still relevant, unless we only want to track this in https://github.com/google/transit/issues/268.

**Comment by derhuerst** [comment]
Still relevant.

**Comment by derhuerst** [comment]
😢 – This is still relevant.

**Comment by derhuerst** [comment]
This is still relevant.

**Pull request closed without merging**
